name: SignLink
version: 0.1
main: uk.co.jacekk.bukkit.signlink.SignLink
permissions:
    signlink.create:
        description: Allows the player to create SignLink signs.
        default: op
    signlink.remove:
        description: Allows the player to remove SignLink signs.
        default: op
    signlink.use:
        description: Allows the player to use SignLink signs.
        default: true